name: crm
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.11.0=py38h50d1736_0
  - alabaster=0.7.12=py_0
  - asteval=0.9.16=pyh5ca1d4c_0
  - attrs=19.3.0=py_0
  - awscli=1.17.13=py38_0
  - babel=2.8.0=py_0
  - botocore=1.14.13=py_0
  - ca-certificates=2020.12.5=h033912b_0
  - certifi=2020.12.5=py38h50d1736_1
  - cffi=1.14.3=py38h9edaa1b_1
  - chardet=3.0.4=py38_1003
  - click=7.0=py_0
  - colorama=0.4.3=py_0
  - coverage=5.3=py38h4d0b108_1
  - cryptography=3.2.1=py38h5c1d3f9_0
  - cycler=0.10.0=py_2
  - dill=0.3.1.1=py38h32f6830_1
  - docutils=0.15.2=py38_0
  - entrypoints=0.3=py38_1000
  - flake8=3.7.9=py38_0
  - freetype=2.10.4=h3f75d11_0
  - idna=2.8=py38_1000
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.6.0=py38h32f6830_0
  - importlib_metadata=1.6.0=0
  - jax=0.2.8=pyhd8ed1ab_0
  - jaxlib=0.1.56=py38h32f6830_0
  - jinja2=2.11.1=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.1=py_0
  - kiwisolver=1.1.0=py38ha1b3eb9_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.1=1
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=h50e675f_13
  - libgfortran4=7.5.0=h50e675f_13
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h3d69b6c_7
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.12.3=hd174df1_1
  - llvm-openmp=11.0.0=h73239a0_1
  - lmfit=1.0.0=py_0
  - markupsafe=1.1.1=py38h94c058a_2
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h11da6c2_0
  - mccabe=0.6.1=py_1
  - more-itertools=8.2.0=py_0
  - ncurses=6.2=h2e338ed_4
  - numpy=1.19.4=py38hcf469a5_1
  - openssl=1.1.1i=h35c211d_0
  - opt_einsum=3.3.0=py_0
  - packaging=20.1=py_0
  - pandas=1.0.5=py38h5fc983b_0
  - patsy=0.5.1=py_0
  - pip=20.0.2=py_2
  - pluggy=0.13.1=py38_0
  - protobuf=3.12.3=py38hc84c608_0
  - py=1.8.1=py_0
  - pyasn1=0.4.8=py_0
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py38_1
  - pyflakes=2.1.1=py_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py38_0
  - pytest=5.4.1=py38h32f6830_0
  - python=3.8.1=hf2284b6_2
  - python-dateutil=2.8.1=py_0
  - python-dotenv=0.10.5=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyyaml=5.2=py38h0b31af3_0
  - readline=8.0=h0678c8f_2
  - requests=2.22.0=py38_1
  - rsa=3.4.2=py_1
  - s3transfer=0.3.3=py38_0
  - scikit-learn=0.22.1=py38h3dc85bc_1
  - scipy=1.4.1=py38h38b60c6_3
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.33.0=h960bd1c_1
  - statsmodels=0.12.1=py38hf3d72b9_1
  - tk=8.6.10=hb0a8c7a_1
  - tornado=6.1=py38h7e3306e_0
  - uncertainties=3.1.2=py38_0
  - urllib3=1.25.7=py38_0
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xlrd=1.2.0=py_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7795811_1010
  - pip:
    - appnope==0.1.0
    - backcall==0.2.0
    - bleach==3.1.5
    - decorator==4.4.2
    - defusedxml==0.6.0
    - ipykernel==5.3.2
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.6
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pyrsistent==0.16.0
    - pyzmq==19.0.1
    - qtconsole==4.7.5
    - qtpy==1.9.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
