name: crm_validation
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - asteval=0.9.16=pyh5ca1d4c_0
  - awscli=1.17.13=py38_0
  - babel=2.8.0=py_0
  - botocore=1.14.13=py_0
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py38h32f6830_0
  - cffi=1.13.2=py38h33e799b_0
  - chardet=3.0.4=py38_1003
  - click=7.0=py_0
  - colorama=0.4.3=py_0
  - coverage=5.0.3=py38h0b31af3_0
  - cryptography=2.8=py38hafa8578_1
  - cycler=0.10.0=py_2
  - docutils=0.15.2=py38_0
  - entrypoints=0.3=py38_1000
  - flake8=3.7.9=py38_0
  - freetype=2.10.0=h24853df_1
  - idna=2.8=py38_1000
  - imagesize=1.2.0=py_0
  - jinja2=2.11.1=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.14.1=py_0
  - kiwisolver=1.1.0=py38ha1b3eb9_0
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcxx=9.0.1=1
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h3d69b6c_7
  - libpng=1.6.37=h2573ce8_0
  - llvm-openmp=9.0.1=h28b9765_2
  - lmfit=1.0.0=py_0
  - markupsafe=1.1.1=py38h0b31af3_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h11da6c2_0
  - mccabe=0.6.1=py_1
  - ncurses=6.1=h0a44026_1002
  - numpy=1.18.1=py38hde6bac1_0
  - openssl=1.1.1f=h0b31af3_0
  - packaging=20.1=py_0
  - pandas=1.0.1=py38h4f17bb1_0
  - patsy=0.5.1=py_0
  - pip=20.0.2=py_2
  - pyasn1=0.4.8=py_0
  - pycodestyle=2.5.0=py_0
  - pycparser=2.19=py38_1
  - pyflakes=2.1.1=py_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.6=py_0
  - pysocks=1.7.1=py38_0
  - python=3.8.1=hf2284b6_2
  - python-dateutil=2.8.1=py_0
  - python-dotenv=0.10.5=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - pyyaml=5.2=py38h0b31af3_0
  - readline=8.0=hcfe32e1_0
  - requests=2.22.0=py38_1
  - rsa=3.4.2=py_1
  - s3transfer=0.3.3=py38_0
  - scikit-learn=0.22.1=py38h3dc85bc_1
  - scipy=1.4.1=py38h82752d6_0
  - setuptools=45.2.0=py38_0
  - six=1.14.0=py38_0
  - snowballstemmer=2.0.0=py_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.30.1=h93121df_0
  - statsmodels=0.11.1=py38h0b31af3_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.3=py38h0b31af3_2
  - uncertainties=3.1.2=py38_0
  - urllib3=1.25.7=py38_0
  - wheel=0.34.2=py_1
  - xlrd=1.2.0=py_0
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.2.2=h0b31af3_1
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/akhilpotla/anaconda3/envs/crm_validation

